// <auto-generated />
using System;
using BlogApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogApi.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20260224172457_InitialSqlite")]
    partial class InitialSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("BlogApi.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Faith",
                            Content = "God’s promises are true even when life is hard. In this post, we explore how to stay faithful...",
                            ImageUrl = "https://images.unsplash.com/photo-1504052434569-70ad5836ab65?q=80&w=1000&auto=format&fit=crop",
                            PublishedDate = new DateTime(2026, 2, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "The Newbreak Church blog takes the message from the weekend and lays out next right steps...",
                            Title = "How to Hold On to God’s Promises During Tough Times"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Growth",
                            Content = "Developing new habits isn't just about willpower; it's about surrender...",
                            ImageUrl = "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?q=80&w=1000&auto=format&fit=crop",
                            PublishedDate = new DateTime(2026, 2, 22, 14, 30, 0, 0, DateTimeKind.Utc),
                            Summary = "Starting the year with spiritual disciplines can transform your walk with Christ.",
                            Title = "A New Year with New Habits"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
