// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantBackend.Data;

#nullable disable

namespace RestaurantBackend.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20260427165644_AddOrderCompletionFields")]
    partial class AddOrderCompletionFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("RestaurantBackend.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "saisagar@123",
                            Role = "Owner",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("RestaurantBackend.Models.MenuCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MenuCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Saisagar Tandoor Tadka"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sandwiches"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fries and Nachos"
                        },
                        new
                        {
                            Id = 4,
                            Name = "All Time Favourite Appetizers"
                        });
                });

            modelBuilder.Entity("RestaurantBackend.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            IsAvailable = true,
                            Name = "Paneer Tikka",
                            Price = 150m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            IsAvailable = true,
                            Name = "Paneer Achari Tikka",
                            Price = 170m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            IsAvailable = true,
                            Name = "Paneer Malai Tikka",
                            Price = 180m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            IsAvailable = true,
                            Name = "Mushroom Tikka",
                            Price = 180m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            IsAvailable = true,
                            Name = "Soya Chaap",
                            Price = 140m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            IsAvailable = true,
                            Name = "Achari Soya Chaap",
                            Price = 150m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            IsAvailable = true,
                            Name = "Afghani Soya Chaap",
                            Price = 170m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            IsAvailable = true,
                            Name = "Tandoori Veg Momos",
                            Price = 140m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            IsAvailable = true,
                            Name = "Afghani Momos",
                            Price = 150m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            IsAvailable = true,
                            Name = "Tandoori Paneer Momos",
                            Price = 150m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            IsAvailable = true,
                            Name = "Tandoori Spring Roll",
                            Price = 150m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            IsAvailable = true,
                            Name = "Veg Sandwich",
                            Price = 100m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            IsAvailable = true,
                            Name = "Masala Sandwich",
                            Price = 100m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            IsAvailable = true,
                            Name = "Schezwan Sandwich",
                            Price = 100m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            IsAvailable = true,
                            Name = "Plain Cheese Sandwich",
                            Price = 100m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            IsAvailable = true,
                            Name = "Cheese Chutney Sandwich",
                            Price = 100m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            IsAvailable = true,
                            Name = "Veg Cheese Sandwich",
                            Price = 120m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            IsAvailable = true,
                            Name = "Masala Cheese Sandwich",
                            Price = 120m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            IsAvailable = true,
                            Name = "Tandoori Veg Sandwich",
                            Price = 120m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            IsAvailable = true,
                            Name = "Tandoori Paneer Sandwich",
                            Price = 120m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            IsAvailable = true,
                            Name = "Corn Capsicum Sandwich",
                            Price = 120m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            IsAvailable = true,
                            Name = "Maggie Sandwich",
                            Price = 140m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            IsAvailable = true,
                            Name = "Nutella Sandwich",
                            Price = 140m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            IsAvailable = true,
                            Name = "French Fries",
                            Price = 90m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            IsAvailable = true,
                            Name = "Plain Nachos",
                            Price = 90m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            IsAvailable = true,
                            Name = "Peri Peri Masala Fries",
                            Price = 100m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            IsAvailable = true,
                            Name = "Mayo Chilli Fries",
                            Price = 130m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            IsAvailable = true,
                            Name = "Cheese Chipotle Fries",
                            Price = 130m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            IsAvailable = true,
                            Name = "Cheesey Peri Peri Fries",
                            Price = 130m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            IsAvailable = true,
                            Name = "Salsa Mexican Fries",
                            Price = 130m
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 3,
                            IsAvailable = true,
                            Name = "Mint Mayo Fries",
                            Price = 130m
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            IsAvailable = true,
                            Name = "Nutella Fries",
                            Price = 130m
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 3,
                            IsAvailable = true,
                            Name = "Mayo Chilli Nachos",
                            Price = 130m
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 3,
                            IsAvailable = true,
                            Name = "Cheese Chipotle Nachos",
                            Price = 130m
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 3,
                            IsAvailable = true,
                            Name = "Cheesey Peri Peri Nachos",
                            Price = 130m
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            IsAvailable = true,
                            Name = "Salsa Mexican Nachos",
                            Price = 130m
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            IsAvailable = true,
                            Name = "Potato Twister",
                            Price = 100m
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            IsAvailable = true,
                            Name = "Special Garlic Bread",
                            Price = 100m
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            IsAvailable = true,
                            Name = "Red Pasta",
                            Price = 140m
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            IsAvailable = true,
                            Name = "White Pasta",
                            Price = 150m
                        });
                });

            modelBuilder.Entity("RestaurantBackend.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrepared")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsServed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TableId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RestaurantBackend.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("RestaurantBackend.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("RestaurantBackend.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TableNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Available",
                            TableNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            Status = "Available",
                            TableNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            Status = "Available",
                            TableNumber = 3
                        });
                });

            modelBuilder.Entity("RestaurantBackend.Models.TableSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TableId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("TableSessions");
                });

            modelBuilder.Entity("RestaurantBackend.Models.MenuItem", b =>
                {
                    b.HasOne("RestaurantBackend.Models.MenuCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RestaurantBackend.Models.Order", b =>
                {
                    b.HasOne("RestaurantBackend.Models.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("RestaurantBackend.Models.OrderItem", b =>
                {
                    b.HasOne("RestaurantBackend.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantBackend.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantBackend.Models.Payment", b =>
                {
                    b.HasOne("RestaurantBackend.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantBackend.Models.TableSession", b =>
                {
                    b.HasOne("RestaurantBackend.Models.Table", "Table")
                        .WithMany("Sessions")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("RestaurantBackend.Models.MenuCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RestaurantBackend.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RestaurantBackend.Models.Table", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
